#!/usr/bin/env python
# -*- coding: utf-8 -*-
# 时间复杂度：O(n^2)
# 稳定性：稳定

def bubble_sort(alist):
    # 遍历次数
    for i in range(len(alist)-1):
        # 每次遍历比较次数呈递减
        for j in range(len(alist)-1-i):
            # 比较前后位置的大小，并交换位置
            if alist[j] > alist[j+1]:
                alist[j], alist[j+1] = alist[j+1], alist[j]
    return alist
