#!/usr/bin/env python
# -*- coding: utf-8 -*-
# 列表被分为有序区和无序区，每次从无序区选择一个元素，插入到有序区的元素，直到无序区变空
# 时间复杂度：O(n^2)
# 稳定性：稳定


def insert_sort(alist):
    # 从第二个数遍历到最后
    for i in range(1, len(alist)):
        # 待插入的数
        key = alist[i]
        j = i - 1
        # 待插入数与已排序号的数进行比较
        while j >=0 and alist[j] > key:
            alist[j+1] = alist[j]
            j -= 1
        alist[j+1] = key
    return alist
