#!/usr/bin/env python
# -*- coding: utf-8 -*-
# 每一次从待排序的数据元素中选出最小（或最大）的一个元素，存放到序列起始位置。
# 时间复杂度：O(n^2),需要进行的比较次数为第一轮 n-1，n-2....1, 总的比较次数为 n*(n-1)/2
# 稳定性：不稳定


def select_sort(alist):
    # 遍历次数
    for i in range(len(alist)-1):
        # 默认设置当前值为最小值
        min = i
        for j in range(i+1, len(alist)):
            # 用默认最小值后的值与最小值比较，以获得最小值下标
            if alist[j] < alist[min]:
                min = j
        alist[i], alist[min] = alist[min], alist[i]
    return alist
